%YAML:1.0
#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
File.version: "1.0"
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV)
# Perfect pinhole camera with square pixels
# FOV : 1.22 rads

# Front Left
Camera1.fx: 329.2
Camera1.fy: 329.2
Camera1.cx: 240.0
Camera1.cy: 240.0
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0

# Front Right
Camera2.fx: 329.2
Camera2.fy: 329.2
Camera2.cx: 240.0
Camera2.cy: 240.0
Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0
Camera2.k3: 0.0

# Transformation matrix from right camera to left camera
Stereo.T_c1_c2: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1.0, 0.0, 0.0, -0.162,  # Baseline 0.162m
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

# # Camera resolution
Camera.width: 480
Camera.height: 480

# Camera frames per second
Camera.fps: 4

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 20000
ORBextractor.scaleFactor: 1.1
ORBextractor.nLevels: 6
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 5

Tracking.thRefRatio: 0.9
Tracking.minFrames: 2
#Tracking.minNumMatches: 5
#Tracking.maxFramesLost: 52

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0 # 500